apiVersion: v1
kind: Service
metadata:
  labels:
    env: dev
  name: external-access
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
